#version: "2.0"
version: "3.9"
services:
  db:
    image: mariadb:10.8.2
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: database
      MYSQL_ROOT_HOST: '%'
    #ports:
    #  - "8889:3306"
  web:
     image: web
     environment:
       - ALLOW_OVERRIDE=true
     ports:
       - "81:80"
     links:
       - db
     volumes:
       - ../ServicioSaludNoAdscrito:/var/www/html/
  

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - 80:80
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: database
